# This workflow will do a clean install of node dependencies and run e2e tests

name: E2E tests

on:
  push:
    branches:
      - main
      - e2e-ci-debug2
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version:
          - 24.x
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload HTML report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            out/report/
            test-results
          retention-days: 30
